services:
  mysql:
    image: mysql:8.0
    container_name: dm_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --sql-mode="" --log-bin-trust-function-creators=1
    volumes:
      - ./bdsolser_md_nieto.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
