// Genera version.js — módulo con la versión del paquete (single source of truth: package.json).
// El archivo queda bundleado dentro del binario compilado (y committeado para que dev funcione sin build).
// Uso: node scripts/generate-version.js (corre dentro del script "build:prepare" del backend)
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const { version } = require(path.join(ROOT, "package.json"));

const out = `// GENERATED by scripts/generate-version.js — no editar a mano
module.exports = ${JSON.stringify(version)};
`;

fs.writeFileSync(path.join(ROOT, "version.js"), out);
console.log(`version.js: ${version}`);
