// Genera assets.js — módulo que embebe client/build + migraciones SQL en el binario compilado.
// Uso: node scripts/generate-assets.js (corre dentro del script "build" del backend)
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const BUILD_DIR = path.join(ROOT, "client", "build");

const files = [];

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(path.relative(ROOT, full));
  }
}

walk(BUILD_DIR);
files.push(path.join("controllers", "employees", "create-table-vendedor-comisiones.sql"));

const normalized = files.map((f) => f.split(path.sep).join("/"));

const imports = normalized.map((f, i) => `import a${i} from "./${f}" with { type: "file" };`);
const entries = normalized.map((f, i) => `  "./${f}": a${i},`);

const out = `// GENERATED by scripts/generate-assets.js — no editar a mano
${imports.join("\n")}

export default {
${entries.join("\n")}
};
`;

fs.writeFileSync(path.join(ROOT, "assets.js"), out);
console.log(`assets.js: ${normalized.length} archivos embebidos`);
